# Generated by Django 5.2.8 on 2026-02-04 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('predicted_category', models.CharField(blank=True, max_length=100, null=True)),
                ('resume_score', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=1)),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_skills', models.TextField(blank=True, default='[]')),
                ('recommended_skills', models.TextField(blank=True, default='[]')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
