# Generated by Django 5.2.8 on 2026-02-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applicant_education_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='category_scores',
            field=models.JSONField(blank=True, help_text='Multi-label category predictions with confidence scores: {category: confidence}', null=True),
        ),
    ]
