# Generated by Django 5.2.8 on 2026-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_applicant_category_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
